/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.product.service.coreapi.events.order;
@org.apache.avro.specific.AvroGenerated
public enum OrderUpdatedStatus implements org.apache.avro.generic.GenericEnumSymbol<OrderUpdatedStatus> {
  PENDING, APPROVED, CANCELED, SHIPPED, DELIVERED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderUpdatedStatus\",\"namespace\":\"com.product.service.coreapi.events.order\",\"symbols\":[\"PENDING\",\"APPROVED\",\"CANCELED\",\"SHIPPED\",\"DELIVERED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
