/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.product.service.coreapi.events.category;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CategoryDeletedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8458748790771948328L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CategoryDeletedEvent\",\"namespace\":\"com.product.service.coreapi.events.category\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"deletedAt\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}]}],\"version\":\"1\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<CategoryDeletedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CategoryDeletedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CategoryDeletedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CategoryDeletedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CategoryDeletedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CategoryDeletedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CategoryDeletedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CategoryDeletedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CategoryDeletedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID id;
  private java.time.Instant deletedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CategoryDeletedEvent() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param deletedAt The new value for deletedAt
   */
  public CategoryDeletedEvent(java.util.UUID id, java.time.Instant deletedAt) {
    this.id = id;
    this.deletedAt = deletedAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return deletedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.util.UUID)value$; break;
    case 1: deletedAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.util.UUID getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.util.UUID value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'deletedAt' field.
   * @return The value of the 'deletedAt' field.
   */
  public java.time.Instant getDeletedAt() {
    return deletedAt;
  }


  /**
   * Sets the value of the 'deletedAt' field.
   * @param value the value to set.
   */
  public void setDeletedAt(java.time.Instant value) {
    this.deletedAt = value;
  }

  /**
   * Creates a new CategoryDeletedEvent RecordBuilder.
   * @return A new CategoryDeletedEvent RecordBuilder
   */
  public static com.product.service.coreapi.events.category.CategoryDeletedEvent.Builder newBuilder() {
    return new com.product.service.coreapi.events.category.CategoryDeletedEvent.Builder();
  }

  /**
   * Creates a new CategoryDeletedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CategoryDeletedEvent RecordBuilder
   */
  public static com.product.service.coreapi.events.category.CategoryDeletedEvent.Builder newBuilder(com.product.service.coreapi.events.category.CategoryDeletedEvent.Builder other) {
    if (other == null) {
      return new com.product.service.coreapi.events.category.CategoryDeletedEvent.Builder();
    } else {
      return new com.product.service.coreapi.events.category.CategoryDeletedEvent.Builder(other);
    }
  }

  /**
   * Creates a new CategoryDeletedEvent RecordBuilder by copying an existing CategoryDeletedEvent instance.
   * @param other The existing instance to copy.
   * @return A new CategoryDeletedEvent RecordBuilder
   */
  public static com.product.service.coreapi.events.category.CategoryDeletedEvent.Builder newBuilder(com.product.service.coreapi.events.category.CategoryDeletedEvent other) {
    if (other == null) {
      return new com.product.service.coreapi.events.category.CategoryDeletedEvent.Builder();
    } else {
      return new com.product.service.coreapi.events.category.CategoryDeletedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for CategoryDeletedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CategoryDeletedEvent>
    implements org.apache.avro.data.RecordBuilder<CategoryDeletedEvent> {

    private java.util.UUID id;
    private java.time.Instant deletedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.product.service.coreapi.events.category.CategoryDeletedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.deletedAt)) {
        this.deletedAt = data().deepCopy(fields()[1].schema(), other.deletedAt);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing CategoryDeletedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.product.service.coreapi.events.category.CategoryDeletedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.deletedAt)) {
        this.deletedAt = data().deepCopy(fields()[1].schema(), other.deletedAt);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.util.UUID getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.product.service.coreapi.events.category.CategoryDeletedEvent.Builder setId(java.util.UUID value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.product.service.coreapi.events.category.CategoryDeletedEvent.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'deletedAt' field.
      * @return The value.
      */
    public java.time.Instant getDeletedAt() {
      return deletedAt;
    }


    /**
      * Sets the value of the 'deletedAt' field.
      * @param value The value of 'deletedAt'.
      * @return This builder.
      */
    public com.product.service.coreapi.events.category.CategoryDeletedEvent.Builder setDeletedAt(java.time.Instant value) {
      validate(fields()[1], value);
      this.deletedAt = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'deletedAt' field has been set.
      * @return True if the 'deletedAt' field has been set, false otherwise.
      */
    public boolean hasDeletedAt() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'deletedAt' field.
      * @return This builder.
      */
    public com.product.service.coreapi.events.category.CategoryDeletedEvent.Builder clearDeletedAt() {
      deletedAt = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CategoryDeletedEvent build() {
      try {
        CategoryDeletedEvent record = new CategoryDeletedEvent();
        record.id = fieldSetFlags()[0] ? this.id : (java.util.UUID) defaultValue(fields()[0]);
        record.deletedAt = fieldSetFlags()[1] ? this.deletedAt : (java.time.Instant) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CategoryDeletedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<CategoryDeletedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CategoryDeletedEvent>
    READER$ = (org.apache.avro.io.DatumReader<CategoryDeletedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










